msg_enable
# auth_add name=munge
# listen xprt=sock port=10001 

load name=meminfo
config name=meminfo instance=${HOSTNAME}/meminfo producer=${HOSTNAME}
start name=meminfo interval=1s

load name=papi_sampler
config name=papi_sampler producer=${HOSTNAME} instance=IGNORED job_expiry=15
start name=papi_sampler interval=1s
